### PR TITLE
IKEA support

### PR DESCRIPTION
**Pull request by Tweska**
Added IKEA support (issue #14), including discount detection.

Note: I added the description to the name of the product because a lot of IKEA products have identical names. This makes the product names really long and then they don't fit in the graph title. So the graph titles only show the official product name without the description. It's not the nicest implementation, perhaps we should add a field for a short product name.

### CODE REVIEW

**Comment by m-rtijn** [comment]
> Note: I added the description to the name of the product because a lot of IKEA products have identical names. This makes the product names really long and then they don't fit in the graph title. So the graph titles only show the official product name without the description. It's not the nicest implementation, perhaps we should add a field for a short product name.

Hmmm, maybe it would be better to add a description field maybe?

**Comment by m-rtijn** [comment]
Also, did you also test it with [ikea.nl](ikea.nl)? As I only see ikea.com in the code

**Comment by Tweska** [comment]
> Also, did you also test it with [ikea.nl](ikea.nl)? As I only see ikea.com in the code

I did not test it with ikea.nl because it redirects me to https://www.ikea.com/nl/nl/

**Comment by Tweska** [comment]
I have added the description field including proper rendering in the templates. Let me know what you think @m-rtijn!

Note that a new column has to be added to the database for this to work in production.

**Comment by m-rtijn** [comment]
Thanks for the contribution! :smile: Sorry it took a while to merge...

**Pull request merged**
